# Generated by Django 5.0.2 on 2024-04-28 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_donationarea_donation_gallery_volunteer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='Volunteer',
        ),
        migrations.AlterField(
            model_name='donation',
            name='adminremark',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donationname',
            field=models.CharField(choices=[('Food Donation', 'Food Donation'), ('Cloth Donation', 'Cloth Donation'), ('Footwear Donation', 'Footwear Donation'), ('Books Donation', 'Books Donation'), ('Furniture Donation', 'Furniture Donation'), ('Vessel Donation', 'Vessel Donation'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='volunteerremark',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='volunteer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.volunteer'),
        ),
    ]
